spring:
  application:
    name: vacancy-service
  profiles:
    active: ${PROFILE:dev}
  jackson:
    property-naming-strategy: SNAKE_CASE
  config:
    import: optional:configserver:http://localhost:${CONFIG_SERVER_PORT:9991}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml

---
spring:
  config:
    activate:
      on-profile: dev

